create table public.practice_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic text not null,
  prompt text not null,
  duration_seconds integer,
  speaking_score integer check (speaking_score between 0 and 100),
  content_score integer check (content_score between 0 and 100),
  organization_score integer check (organization_score between 0 and 100),
  relevance_score integer check (relevance_score between 0 and 100),
  pace_wpm integer,
  filler_count integer not null default 0,
  repetition_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.practice_attempts enable row level security;

revoke all on table public.practice_attempts from anon;
grant select, insert on table public.practice_attempts to authenticated;
grant usage, select on sequence public.practice_attempts_id_seq to authenticated;

create policy "Users can read their own practice attempts"
on public.practice_attempts for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can save their own practice attempts"
on public.practice_attempts for insert
to authenticated
with check ((select auth.uid()) = user_id);

